site_name: My Docs
nav:
  - Home: index.md
  - Set Theory:
      - Lecture 2: set-theory/lecture-02.md
      - Lecture 3: set-theory/lecture-03.md
      - Lecture 4: set-theory/lecture-04.md
      - Lecture 5: set-theory/lecture-05.md
      - Lecture 6: set-theory/lecture-06.md

theme:
  name: dracula

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
